# Run `conda-env create -f install_gds_stack.yml`
name: gds
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - geopandas
  - ipywidgets
  - jupyterlab
  - mplleaflet
  - palettable
  - pip:
        - contextily==1.0rc2
  - pysal==2.1
  - rasterio
  - scikit-learn
  - seaborn
  - statsmodels
  - xlrd
  - xlsxwriter
